apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: where-for-dinner-search-rmq
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"where-for-dinner-search","apps.tanzu.vmware.com/workload-type":"web","networking.knative.dev/visibility":"cluster-local"},"name":"where-for-dinner-search","namespace":"my-apps"},"spec":{"env":[{"name":"spring_profiles_active","value":"mysql"}],"params":[{"name":"gitops_repository","value":"ssh://git@github.com/dapdelivery/where-for-dinner-dest-22-02-2023-13-17-50-104967261.git"},{"name":"gitops_ssh_secret","value":"git-ssh"}],"serviceClaims":[{"name":"rmq","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"rmq-where-for-dinner"}},{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"mysql-where-for-dinner"}}],"source":{"git":{"ref":{"branch":"main"},"url":"ssh://git@github.com/dapdelivery/where-for-dinner-22-02-2023-13-17-50-104967261.git"},"subPath":"where-for-dinner-search"}}}
  labels:
    app.kubernetes.io/part-of: where-for-dinner-search
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: where-for-dinner-search
spec:
  name: rmq
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: rmq-where-for-dinner
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: where-for-dinner-search
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: where-for-dinner-search-db
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"where-for-dinner-search","apps.tanzu.vmware.com/workload-type":"web","networking.knative.dev/visibility":"cluster-local"},"name":"where-for-dinner-search","namespace":"my-apps"},"spec":{"env":[{"name":"spring_profiles_active","value":"mysql"}],"params":[{"name":"gitops_repository","value":"ssh://git@github.com/dapdelivery/where-for-dinner-dest-22-02-2023-13-17-50-104967261.git"},{"name":"gitops_ssh_secret","value":"git-ssh"}],"serviceClaims":[{"name":"rmq","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"rmq-where-for-dinner"}},{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"mysql-where-for-dinner"}}],"source":{"git":{"ref":{"branch":"main"},"url":"ssh://git@github.com/dapdelivery/where-for-dinner-22-02-2023-13-17-50-104967261.git"},"subPath":"where-for-dinner-search"}}}
  labels:
    app.kubernetes.io/part-of: where-for-dinner-search
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: where-for-dinner-search
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: mysql-where-for-dinner
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: where-for-dinner-search

